### ISSUE TITLE
[bug] edit authentication  error

### ISSUE THREAD

**Issue by li-keguo** [apache/incubator-shenyu-dashboard#203]
create authentication
edit it

<img width="548" alt="image" src="https://user-images.githubusercontent.com/33576070/163819786-e8551434-130a-4877-8119-7ca44ffe3b02.png">
input value is error 

<img width="1055" alt="image" src="https://user-images.githubusercontent.com/33576070/163820494-211bcb4f-ae71-4830-a3d5-f45f3876a619.png">

```log
index.46b4bede.js:18 Uncaught TypeError: Cannot set properties of undefined (setting 'path')
    at t.r.handleTableInput (index.46b4bede.js:18:1598075)
    at onChange (index.46b4bede.js:18:1598483)
    at b (index.46b4bede.js:18:1858210)
    at r.handleChange (index.46b4bede.js:18:1859673)
    at Object.o (index.46b4bede.js:18:58526)
    at a (index.46b4bede.js:18:58609)
    at i (index.46b4bede.js:18:58664)
    at c (index.46b4bede.js:18:58828)
    at ie (index.46b4bede.js:18:68698)
    at Array.forEach (<anonymous>)
```

**Comment by li-keguo** [comment]
We will continue to optimize the logic of adding app parameters
